sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=redoracle/roundcubemail

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build --compress	 -t "${IMAGE_NAME}:latest" .

after_script:

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
